# Generated by Django 5.1.1 on 2025-10-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('hours', models.IntegerField()),
                ('split', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('model_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('subjclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('skillsreq', models.CharField(max_length=1000)),
                ('subjclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('mapped_skill', models.CharField(max_length=100)),
                ('teacherweight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('studentweight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
            ],
        ),
    ]
