# Generated by Django 5.1.1 on 2025-10-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='class_id',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='subjclass',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='subjclass',
            new_name='course',
        ),
    ]
