# Generated by Django 5.1.1 on 2025-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_class_course_rename_class_id_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
