# Generated by Django 5.1.1 on 2025-10-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teacher_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='model_id',
            new_name='module_id',
        ),
    ]
