# Generated by Django 5.1.1 on 2025-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_model_id_module_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
