# Generated by Django 5.1.1 on 2025-10-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regno',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
