# Generated by Django 4.1.13 on 2026-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='accepting_response',
            field=models.BooleanField(default=True),
        ),
    ]
